- name: Ensure wheel group is present
  group:
    name: wheel
    state: present

- name: Ensure wheel group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vim
    - sudo
    - gcc
    - libgfortran
    - unzip
    - screen
    - python3-pip
